{% set name = "flask-injector" %}
{% set version = "0.13.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-Injector-{{ version }}.tar.gz
  sha256: d527f82dfa118acd3011da02edeef855ac7ec656383e2cb6b811071f4f6364a3

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - flask
    - injector >=0.10.0
    - python >=3.6

test:
  imports:
    - flask_injector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alecthomas/flask_injector
  summary: Adds Injector, a Dependency Injection framework, support to Flask.
  # License file manually packaged: See: https://github.com/alecthomas/flask_injector/pull/58
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - fuglede
