{% set name = "flask-injector" %}
{% set version = "0.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/Flask-Injector-{{ version }}.tar.gz
  sha256: f116c24bb3e3e34ca3e41a940eab6178ede41954d27bb02f8a044f128d750dbc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - flask >= 2.1.2
    - injector >=0.20.0
    - python >=3.7

test:
  imports:
    - flask_injector
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/alecthomas/flask_injector
  summary: Adds Injector, a Dependency Injection framework, support to Flask.
  # License file manually packaged: See: https://github.com/alecthomas/flask_injector/pull/58
  license: BSD-3-Clause
  license_file: COPYING

extra:
  recipe-maintainers:
    - fuglede
